apiVersion: v2
name: ahibbert
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: minio
    version: 8.0.10
    repository: https://helm.min.io
    condition: minio.enabled

